### ISSUE TITLE
Grand Teton Example Broken

### ISSUE THREAD

**Issue by kylebarron** [heremaps/harp-terrain-datasource#18]
The [main example](https://heremaps.github.io/harp-terrain-datasource/) is broken. It's trying to load quantized mesh tiles from 
```
https://nikgarmash.com/grand-teton-tiles/tiles/14/3164/10425.terrain
```
but it looks like that should be changed to:
```
https://mykolaharmash.github.io/grand-teton-tiles/tiles/{z}/{x}/{y}.terrain
```

**Comment by mykolaharmash** [comment]
Hi! You're right, [here is a PR](https://github.com/heremaps/harp-terrain-datasource/pull/19) with the fix. Thank you!
